// Generated by https://quicktype.io

export interface Data {
    content:          Content[];
    number:           number;
    size:             number;
    totalElements:    number;
    pageable:         Pageable;
    last:             boolean;
    totalPages:       number;
    sort:             Sort;
    first:            boolean;
    numberOfElements: number;
    empty:            boolean;
}

export interface Content {
    id:                     number;
    typeLicense:            TypeLicense;
    days:                   number;
    initDate:               string;
    medicDiagnostic:        MedicDiagnostic;
    acceptanceStatement:    boolean;
    assignationType:        string;
    medicCenter:            null;
    approvedDays:           number;
    codeOfEmployed:         null;
    endingDate:             string;
    medicalCertificateDate: string;
    birthDate:              null;
    neonatology:            boolean;
    neonatologyDays:        null;
    multipleBirth:          boolean;
    numberOfchildren:       null;
    probableBirthDate:      null;
    fitToWork:              boolean;
    jobSector:              JobSector;
    gcbaLicenseStatus:      string;
    organizationalUnits:    OrganizationalUnit[];
    licenseTypesGroup:      LicenseTypesGroup;
    medicalDecisions:       any[];
    user:                   User;
    appointmentDate:        null;
    observations:           null | string;
}

export interface JobSector {
    id:          number;
    created:     string;
    updated:     string;
    code:        string;
    description: string;
}

export interface LicenseTypesGroup {
    id:          number;
    description: string;
}

export interface MedicDiagnostic {
    id:           string;
    key:          string;
    description:  string;
    category:     string;
    ter:          number;
    autoDecision: string;
}

export interface OrganizationalUnit {
    id:            number;
    created:       string;
    updated:       string;
    codeOU:        string;
    descriptionOU: string;
    jobPositions:  JobPosition[];
}

export interface JobPosition {
    id:                     number;
    created:                string;
    updated:                string;
    jobPositionCode:        string;
    jobPositionDescription: string;
    jobPositionNumericCode: number;
}

export interface TypeLicense {
    id:           number;
    key:          string;
    description:  string;
    type:         string;
    relationship: null;
}

export interface User {
    id:         number;
    businessId: string;
    tenant:     string;
    name:       string;
    surname:    string;
    cuil:       string;
}

export interface Pageable {
    sort:       Sort;
    offset:     number;
    pageNumber: number;
    pageSize:   number;
    paged:      boolean;
    unpaged:    boolean;
}

export interface Sort {
    sorted:   boolean;
    unsorted: boolean;
    empty:    boolean;
}
